task_name: subpopulation_shift
dataset_name: waterbirds
class_list:
  - landbird
  - waterbird
caption_csv: captions/waterbirds/{class_name}/{mllm_name}/{class_name}_caption_{mllm_name}.csv
num_class: 0  # subpopulation shift default = 0